X = input()
Y = input()
Z = input()

print("The"+ " "+ X + " " + "on the bus" + " " + Y)
print(Z)
print(Z)
print(Z)
print("The"+ " "+ X + " " + "on the bus" + " " + Y)
print(Z)
print("All through the town")